##
# radio_player.yaml
#
# Radio player
#
# @category   Home Assistant
# @package    Component packages
# @author     Jeroen Butenaerts
# @version    1.0
##
input_select:
  radio_player_input:
    name: 'Stream'
    icon: 'mdi:radio-tower'
    options:
      - 'NPO Radio 1'
      - 'NPO Radio 2'
      - 'NPO 3FM'
      - 'VRT Studio Brussel'

  radio_player_output:
    name: 'Speakers'
    icon: 'mdi:speaker-wireless'
    options:
      - 'Kelder'
      - 'Overloop'
      - 'Slaapkamer'
      - 'Woonkamer'
    initial: 'Woonkamer'

##
# Script
##
script:
  radio_player_start:
    alias: 'Play stream'
    sequence:
      # Set volume on selected media player
      - service: media_player.volume_set
        data_template:
          entity_id: >
            {% if is_state('input_select.radio_player_input', 'Kelder') %}
              media_player.googlehome_basement
            {% elif is_state('input_select.radio_player_input', 'Overloop') %}
              media_player.googlehome_landing
            {% elif is_state('input_select.radio_player_input', 'Slaapkamer') %}
              media_player.chromecast_bedroom
            {% elif is_state('input_select.radio_player_input', 'Woonkamer') %}
              media_player.chromecast_living
            {% endif %}
          volume_level: '0.35'
      # Play selected stream on selected media player
      - service: media_player.play_media
        data_template:
          entity_id: >
            {% if is_state('input_select.radio_player_input', 'Kelder') %}
              media_player.googlehome_basement
            {% elif is_state('input_select.radio_player_input', 'Overloop') %}
              media_player.googlehome_landing
            {% elif is_state('input_select.radio_player_input', 'Slaapkamer') %}
              media_player.chromecast_bedroom
            {% elif is_state('input_select.radio_player_input', 'Woonkamer') %}
              media_player.chromecast_living
            {% endif %}
          media_content_id: >
            {% if is_state('input_select.radio_player_output', 'NPO Radio 1') %}
              http://icecast.omroep.nl/radio1-bb-mp3
            {% elif is_state('input_select.radio_player_output', 'NPO Radio 2') %}
              http://icecast.omroep.nl/radio2-bb-mp3
            {% elif is_state('input_select.radio_player_output', 'NPO 3FM') %}
              http://icecast.omroep.nl/3fm-bb-mp3
            {% elif is_state('input_select.radio_player_output', 'NPO Radio 4') %}
              http://icecast.omroep.nl/radio2-bb-mp3
            {% elif is_state('input_select.radio_player_output', 'VRT Studio Brussel') %}
              http://icecast.vrtcdn.be/stubru-high.mp3
            {% endif %}
          media_content_type: 'audio/mp4'

##
# Group
##
group:
  radio_player:
    name: 'Radio player'
    control: false
    entities:
      - input_select.radio_player_input
      - input_select.radio_player_output
      - script.radio_player_start

##
# Customize
##
homeassistant:
  customize:
    group.radio_player:
      friendly_name: 'Radio'
      icon: 'mdi:radio'

    script.radio_player_start:
      friendly_name: 'Stream afspelen'
      icon: 'mdi:play'
