##
# sun.yaml
#
# Sun
#
# @category   Home Assistant
# @package    Component packages
# @author     Jeroen Butenaerts
# @version    1.0
##
sun:

##
# Customize
##
homeassistant:
  customize:
    sun.sun:
      friendly_name: 'Zon'
      hidden: true
