##
# time_date.yaml
#
# Time/date sensor
#
# @category   Home Assistant
# @package    Component packages
# @author     Jeroen Butenaerts
# @version    1.0
##
sensor:
  - platform: time_date
    display_options:
      - 'time'
#      - 'date'
#      - 'date_time'
#      - 'date_time_iso'
#      - 'time_date'
#      - 'time_utc'
#      - 'beat'
##
# Customize
##
homeassistant:
  customize:
    sensor.time:
      friendly_name: 'Tijd'
      hidden: true
