##
# scene_general_evening.yaml
#
# Set up for watching tv
#
# @category   Home Assistant
# @package    Scenes
# @author     Jeroen Butenaerts
# @version    1.0
##
scene:
  - name: 'general_evening'
    entities:
      light.fibaro_system_fgd212_dimmer_2_level_4: # Living
        state: on
        brightness_pct: 1
        transition: 2
      light.tv_lamp:
        state: on
        brightness_pct: 25
        transition: 2
      light.fibaro_system_fgd212_dimmer_2_level_2: # Dining
        state: on
        brightness_pct: 1
        transition: 2
      light.kastverlichting:
        state: on
        brightness_pct: 50
        transition: 2
      light.livingwhites_plug_1:
        state: on
        brightness_pct: 25
        transition: 2
      light.fibaro_system_fgd212_dimmer_2_level_11: # Kitchen
        state: off
        transition: 2
      light.werkbladverlichting:
        state: on
        brightness_pct: 25
        transition: 2

##
# Customize
##
homeassistant:
  customize:
    scene.general_evening:
      friendly_name: 'Algemeen (avond)'
      icon: 'mdi:weather-sunset-down'
