##
# postnl.yaml
#
# PostNL delivery tracking
#
# @category   Home Assistant
# @package    Service packages
# @author     Jeroen Butenaerts
# @version    1.0
##

##
# Components
##
sensor:
  - platform: postnl
    username: !secret postnl_username
    password: !secret postnl_password

##
# Customize
##

##
# Groups
##

##
# Scenes
##

##
# Automation
##

##
# Scripts
##
