##
# door_window_sensor_158d0001b77e9a.yaml
#
# Xiaomi Aqara door/window sensor
#
# @category   Home Assistant
# @package    Devices
# @author     Jeroen Butenaerts
# @version    1.0
##
sensor:
  - platform: template
    sensors:
      door_window_sensor_158d0001b77e9a_battery:
        device_class: battery
        unit_of_measurement: '%'
        value_template: "{{ state_attr('binary_sensor.door_window_sensor_158d0001b77e9a', 'battery_level')|int }}"
        icon_template: >
          {% set battery_level = state_attr('binary_sensor.door_window_sensor_158d0001b77e9a', 'battery_level')|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}

##
# Customize
##
homeassistant:
  customize:
    binary_sensor.door_window_sensor_158d0001b77e9a:
      device_class: window
      friendly_name: 'Keukenraam rechts'
      hidden: true

    sensor.door_window_sensor_158d0001b77e9a_battery:
      friendly_name: 'Batterij deur-/raamcontact keukenraam rechts'

  customize_glob:
    sensor.door_window_sensor_158d0001b77e9a_battery:
      group:
        group.battery_levels:
          friendly_name: 'Deur-/raamcontact keukenraam rechts'
