##
# door_window_sensor_158d0001ab5797.yaml
#
# Xiaomi Aqara door/window sensor
#
# @category   Home Assistant
# @package    Devices
# @author     Jeroen Butenaerts
# @version    1.0
##
sensor:
  - platform: template
    sensors:
      door_window_sensor_158d0001ab5797_battery:
        device_class: battery
        unit_of_measurement: '%'
        value_template: "{{ state_attr('binary_sensor.door_window_sensor_158d0001ab5797', 'battery_level')|int }}"
        icon_template: >
          {% set battery_level = state_attr('binary_sensor.door_window_sensor_158d0001ab5797', 'battery_level')|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}

##
# Customize
##
homeassistant:
  customize:
    binary_sensor.door_window_sensor_158d0001ab5797:
      device_class: window
      friendly_name: 'Studeerkamerraam'

    sensor.door_window_sensor_158d0001ab5797_battery:
      friendly_name: 'Batterij deur-/raamcontact studeerkamerraam'
#      templates:
#        theme: >
#          {% if states('sensor.door_window_sensor_158d0001ab5797_battery')|int < 5 %}
#            alert-danger
#          {% elif states('sensor.door_window_sensor_158d0001ab5797_battery')|int < 10 %}
#            alert-warning
#          {% endif %}
      templates:
        theme: >
          if (state < 5) {
            return 'alert-danger';
          } else if (state < 10) {
            return 'alert-warning';
          }

  customize_glob:
    sensor.door_window_sensor_158d0001ab5797_battery:
      group:
        group.battery_levels:
          friendly_name: 'Deur-/raamcontact studeerkamerraam'
