##
# door_window_sensor_158d0001f38318.yaml
#
# Xiaomi Aqara door/window sensor
#
# @category   Home Assistant
# @package    Devices
# @author     Jeroen Butenaerts
# @version    1.0
##

##
# Components
##

binary_sensor:
  - platform: template
    sensors:
      door_window_sensor_158d0001f38318_battery_low:
        device_class: battery
        value_template: '{{ states.binary_sensor.door_window_sensor_158d0001f38318.attributes.battery_level < 5 }}'

sensor:
  - platform: template
    sensors:
      door_window_sensor_158d0001f38318_battery:
        device_class: battery
        friendly_name: 'Batterij deur-/raamsensor tuindeuren'
        unit_of_measurement: '%'
        value_template: '{{ states.binary_sensor.door_window_sensor_158d0001f38318.attributes.battery_level|int }}'
        icon_template: >
          {% set battery_level = states.sensor.door_window_sensor_158d0001f38318_battery.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}

##
# Customize
##
homeassistant:
  customize:
    binary_sensor.door_window_sensor_158d0001f38318:
      device_class: door
      friendly_name: 'Tuindeuren'

    sensor.door_window_sensor_158d0001f38318_battery:
      templates:
        theme: >
          if (state < 5) {
            return 'alert-danger';
          } else if (state < 10) {
            return 'alert-warning';
          }

    binary_sensor.door_window_sensor_158d0001f38318_battery_low:
      hidden: true

    sensor.door_window_sensor_garden_doors:
      templates:
        rgb_color: 'if (state === "on") return [213, 0, 0]; elif (state === "off") return [255, 160, 0]; else return [56, 142, 60];'

  customize_glob:
    sensor.door_window_sensor_158d0001f38318_battery:
      group:
        group.battery_levels:
          friendly_name: Deur-/raamsensor tuindeuren

##
# Groups
##

##
# Scenes
##

##
# Alerts
##
alert:
  door_window_sensor_158d0001f38318_battery_low:
    name: Batterijniveau deur-/raamcontact tuindeuren onder 5%
    entity_id: binary_sensor.door_window_sensor_158d0001f38318_battery_low
    repeat: 1440
    notifiers:
      - user_1
      - user_2

##
# Automation
##

##
# Scripts
##
