##
# natgas_sensor_158d000127c558.yaml
#
# Xiaomi Mijia natural gas sensor
#
# @category   Home Assistant
# @package    Devices
# @author     Jeroen Butenaerts
# @version    1.0
##
##
# Customize
##
homeassistant:
  customize:
    binary_sensor.natgas_sensor_158d000127c558:
      device_class: gas
      friendly_name: 'Aardgas meterkast'

  customize_glob:
    binary_sensor.natgas_sensor_158d000127c558:
      group:
        group.security_natgas:
          friendly_name: 'Meterkast'
