##
# natgas_sensor_158d00011176ee.yaml
#
# Xiaomi Mijia natural gas sensor
#
# @category   Home Assistant
# @package    Devices
# @author     Jeroen Butenaerts
# @version    1.0
##

##
# Components
##

##
# Customize
##
homeassistant:
  customize:
    binary_sensor.natgas_sensor_158d00011176ee:
      device_class: gas
      friendly_name: 'Gasmelder centrale verwarming'

  customize_glob:
    binary_sensor.natgas_sensor_158d00011176ee:
      group:
        group.security_gas:
          friendly_name: Centrale verwarming

##
# Groups
##

##
# Scenes
##

##
# Alerts
##
alert:
  natgas_sensor_158d00011176ee_leak_detected:
    name: Gaslek centrale verwarming gedetecteerd
    entity_id: binary_sensor.natgas_sensor_158d00011176ee
    repeat: 15
    notifiers:
      - user_1
      - user_2

##
# Automation
##

##
# Scripts
##
