##
# smoke_sensor.yaml
#
# Xiaomi Aqara smoke sensor
#
# @category   Home Assistant
# @package    Devices
# @author     Jeroen Butenaerts
# @version    1.0
##
binary_sensor:
  ##
  # All combined
  ##
  - platform: template
    sensors:
      smoke_sensor_all:
        device_class: smoke
        value_template: >-
          {{ is_state('binary_sensor.smoke_sensor_158d0001e80a3c', 'on')
             or is_state('binary_sensor.smoke_sensor_158d0001e80a40', 'on')
             or is_state('binary_sensor.smoke_sensor_158d000215e268', 'on')
             or is_state('binary_sensor.smoke_sensor_158d000215e643', 'on')
             or is_state('binary_sensor.smoke_sensor_158d000215a794', 'on')
             or is_state('binary_sensor.smoke_sensor_158d0002153aba', 'on') }}

##
# Customize
##
homeassistant:
  customize:
    binary_sensor.smoke_sensor_all:
      friendly_name: 'Rook'
