##
# temperature_sensor_158d0002288396.yaml
#
# Xiaomi Aqara temperature sensor
#
# @category   Home Assistant
# @package    Devices
# @author     Jeroen Butenaerts
# @version    1.0
##
sensor:
  - platform: template
    sensors:
      temperature_158d0002288396_battery:
        device_class: battery
        unit_of_measurement: '%'
        value_template: "{{ state_attr('sensor.temperature_158d0002288396', 'battery_level')|int }}"
        icon_template: >
          {% set battery_level = state_attr('sensor.temperature_158d0002288396', 'battery_level')|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}

##
# Customize
##
homeassistant:
  customize:
    sensor.humidity_158d0002288396:
      friendly_name: 'Luchtvochtigheid wasruimte'
      icon: 'mdi:water-percent'

    sensor.pressure_158d0002288396:
      friendly_name: 'Luchtdruk wasruimte'
      icon: 'mdi:gauge'

    sensor.temperature_158d0002288396:
      friendly_name: 'Temperatuur wasruimte'
      icon: 'mdi:thermometer'

    sensor.temperature_158d0002288396_battery:
      friendly_name: 'Batterij temperatuursensor wasruimte'

  customize_glob:
    sensor.humidity_158d0002288396:
      group:
        group.climate_boiler_room:
          friendly_name: 'Luchtvochtigheid'
        history_graph.luchtvochtigheid:
          friendly_name: 'Wasruimte'

    sensor.pressure_158d0002288396:
      group:
        group.climate_boiler_room:
          friendly_name: 'Luchtdruk'

    sensor.temperature_158d0002288396:
      group:
        group.climate_boiler_room:
          friendly_name: 'Temperatuur'
        history_graph.temperatuur:
          friendly_name: 'Wasruimte'

    sensor.temperature_158d0002288396_battery:
      group:
        group.battery_levels:
          friendly_name: 'Temperatuursensor wasruimte'
