##
# water_leak_sensor_158d0001bc19c5.yaml
#
# Xiaomi Aqara water leak sensor
#
# @category   Home Assistant
# @package    Devices
# @author     Jeroen Butenaerts
# @version    1.0
##

##
# Components
##

binary_sensor:
  - platform: template
    sensors:
      water_leak_sensor_158d0001bc19c5_battery_low:
        device_class: battery
        value_template: '{{ states.binary_sensor.water_leak_sensor_158d0001bc19c5.attributes.battery_level < 5 }}'

sensor:
  - platform: template
    sensors:
      water_leak_sensor_158d0001bc19c5_battery:
        device_class: battery
        friendly_name: 'Batterij waterlekkagesensor waterpomp'
        unit_of_measurement: '%'
        value_template: '{{ states.binary_sensor.water_leak_sensor_158d0001bc19c5.attributes.battery_level|int }}'
        icon_template: >
          {% set battery_level = states.sensor.water_leak_sensor_158d0001bc19c5_battery.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}

##
# Customize
##
homeassistant:
  customize:
    binary_sensor.water_leak_sensor_158d0001bc19c5:
      device_class: moisture
      friendly_name: 'Waterlekkagesensor waterpomp'

    sensor.water_leak_sensor_158d0001bc19c5_battery:
      templates:
        theme: >
          if (state < 5) {
            return 'alert-danger';
          } else if (state < 10) {
            return 'alert-warning';
          }

    binary_sensor.water_leak_sensor_158d0001bc19c5_battery_low:
      hidden: true

    sensor.water_leak_sensor_waterpump:
      templates:
        rgb_color: 'if (state === "on") return [213, 0, 0]; elif (state === "off") return [255, 160, 0]; else return [56, 142, 60];'

  customize_glob:
    binary_sensor.water_leak_sensor_158d0001bc19c5:
      group:
        group.security_moisture:
          friendly_name: Waterpomp

    sensor.water_leak_sensor_158d0001bc19c5_battery:
      group:
        group.battery_levels:
          friendly_name: Waterlekkagesensor waterpomp

##
# Groups
##

##
# Scenes
##

##
# Alerts
##
alert:
  water_leak_sensor_158d0001bc19c5_battery_low:
    name: Batterijniveau lekkagesensor pomp onder 5%
    entity_id: binary_sensor.water_leak_sensor_158d0001bc19c5_battery_low
    repeat: 1440
    notifiers:
      - user_1
      - user_2

  water_leak_sensor_158d0001bc19c5_leak_detected:
    name: Waterlekkage pomp gedetecteerd
    entity_id: binary_sensor.water_leak_sensor_158d0001bc19c5
    repeat: 15
    notifiers:
      - user_1
      - user_2

##
# Automation
##

##
# Scripts
##
