##
# settings.yaml
#
# Settings group
#
# @category   Home Assistant
# @package    Groups
# @author     Jeroen Butenaerts
# @version    1.0
##
group:
  # Alarm
  settings_alarm:
    name: 'Alarm'
    icon: 'mdi:alarm-light-outline'
    entities:
      - input_number.alarm_entry_delay_time
      - input_number.alarm_exit_delay_time
      - input_number.alarm_trigger_time
      - script.alarm_trigger_test

  # Alarm notification
  settings_alarm_notification:
    name: 'Alarm notification'
    icon: 'mdi:alarm-light-outline'
    entities:
      - input_text.alarm_trigger_title
      - input_text.alarm_trigger_moisture_title
      - input_text.alarm_trigger_moisture_message
      - input_text.alarm_trigger_moisture_color
      - input_text.alarm_trigger_motion_title
      - input_text.alarm_trigger_motion_message
      - input_text.alarm_trigger_motion_color
      - input_text.alarm_trigger_natgas_title
      - input_text.alarm_trigger_natgas_message
      - input_text.alarm_trigger_natgas_color
      - input_text.alarm_trigger_opening_title
      - input_text.alarm_trigger_opening_message
      - input_text.alarm_trigger_opening_color
      - input_text.alarm_trigger_smoke_title
      - input_text.alarm_trigger_smoke_message
      - input_text.alarm_trigger_smoke_color
      - input_text.alarm_trigger_default_title
      - input_text.alarm_trigger_default_message
      - input_text.alarm_trigger_default_color

  # Covers
  settings_covers:
    name: 'Covers'
    icon: 'mdi:alarm-light-outline'
    entities:
      - input_number.covers_ground_auto_open_close_dawn_dusk_lux_threshold
      - input_datetime.covers_ground_auto_open_dawn_time
      - input_datetime.covers_ground_auto_close_dusk_time

  # Presence simulation
  settings_presence_simulation:
    name: 'Presence simulation'
    icon: 'mdi:alarm-light-outline'
    entities:
      - input_datetime.light_all_presence_simulation_waketime
      - input_datetime.light_all_presence_simulation_departuretime
      - input_datetime.light_all_presence_simulation_arrivaltime
      - input_datetime.light_all_presence_simulation_sleeptime

##
# Customize
##
homeassistant:
  customize:
    group.settings_alarm:
      friendly_name: 'Alarm'
      order: 1

    group.settings_alarm_notification:
      friendly_name: 'Alarmmelding'
      order: 2

    group.settings_presence_simulation:
      friendly_name: 'Aanwezigheidssimulatie'
      order: 3

    group.settings_covers:
      friendly_name: 'Raambekleding'
      order: 4
