##
# light_ground_floor_turn_off_no_motion_night.yaml
#
# Turn the lights on the ground floor off at night when no motion
#
# @category   Home Assistant
# @package    Automations
# @author     Jeroen Butenaerts
# @version    1.0
##
automation:
  ##
  # Turn off all lights on the ground floor when no motion is detected at night
  ##
  - alias: 'light_ground_floor_turn_off_no_motion_detected_night'
    initial_state: on
    trigger:
      # When no motion is detected for 60 minutes
      - platform: state
        entity_id: binary_sensor.motion_sensor_ground_floor_all
        to: 'off'
        for:
          minutes: 60
      # Or the time is 0:00
      - platform: time
        at: '00:00:00'
    condition:
      # While time is between 0:00 and 6:00
      - condition: time
        after: '00:00:00'
        before: '06:00:00'
      # And any of the ground floor lights are on
      - condition: state
        entity_id: light.ground_floor_all
        state: 'on'
      # And no motion is detected for 60 minutes
      - condition: state
        entity_id: binary_sensor.motion_sensor_ground_floor_all
        state: 'off'
        for:
          minutes: 60
      # And presence simulation is not active
      - condition: state
        entity_id: input_boolean.light_all_presence_simulation_active
        state: 'off'
    action:
      # Then turn off all lights
      - service: light.turn_off
        data:
          entity_id: light.ground_floor_all
      - service: persistent_notification.create
        data_template:
          title: "Lichten BG uit"
          message: "60 min lang geen geweging gedetecteerd sinds {{ now().strftime('%H:%M') }}"

##
# Customize
##
homeassistant:
  customize:
    automation.light_ground_floor_turn_off_no_motion_detected_night:
      friendly_name: 'Licht begane grond uit bij geen beweging s nachts'
      hidden: true
