##
# light_boiler_room_turn_on_motion.yaml
#
# Turn on the boiler room ceiling light when motion is detected, auto off after 5 minutes
#
# @category   Home Assistant
# @package    Automations
# @author     Jeroen Butenaerts
# @version    1.0
##
input_boolean:
  light_boiler_room_turn_on_motion_detected:
    initial: 'off'

automation:
  ##
  # Turn boiler room light on when motion is detected
  ##
  - alias: 'Light boiler room turn on motion detected'
    initial_state: on
    trigger:
      # When motion is detected
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0002e275dd
      to: 'on'
    condition:
      # While the light is off for at least 10 seconds
      condition: state
      entity_id: light.fibaro_system_fgd212_dimmer_2_level_17
      state: 'off'
      for:
        seconds: 10
    action:
      # Then turn the light on
      - service: light.turn_on
        data:
          entity_id: light.fibaro_system_fgd212_dimmer_2_level_17
      # And register it
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.light_boiler_room_turn_on_motion_detected
  ##
  # Turn light off when no motion is detected
  # - after 5 minutes when light was turned on through motion
  # - or after 60 minutes in any case
  ##
  - alias: 'Light boiler room turn off no motion detected'
    initial_state: on
    trigger:
      # When no motion is detected for 5 minutes
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0002e275dd
      to: 'off'
      for:
        minutes: 5
    condition:
      condition: or
      conditions:
        # While there is a registration
        - condition: state
          entity_id: input_boolean.light_boiler_room_turn_on_motion_detected
          state: 'on'
        # Or there was no motion for 60 minutes
        - condition: state
          entity_id: binary_sensor.motion_sensor_158d0002e275dd
          state: 'off'
          for:
            minutes: 60
    action:
      # Then turn the light off
      service: light.turn_off
      data:
        entity_id: light.fibaro_system_fgd212_dimmer_2_level_17
  ##
  # Reset detection when light is turned off
  ##
  - alias: 'Light boiler room turn on motion detected reset'
    initial_state: on
    trigger:
      # When the light is turned off
      platform: state
      entity_id: light.fibaro_system_fgd212_dimmer_2_level_17
      to: 'off'
    action:
      # Then clear the registration
      service: input_boolean.turn_off
      data:
        entity_id: input_boolean.light_boiler_room_turn_on_motion_detected

##
# Customize
##
homeassistant:
  customize:
    automation.light_boiler_room_turn_on_motion_detected:
      friendly_name: 'Licht wasruimte aan bij beweging'
      hidden: true

    automation.light_boiler_room_turn_off_no_motion_detected:
      friendly_name: 'Licht wasruimte uit bij geen beweging'
      hidden: true

    automation.light_boiler_room_turn_on_motion_detected_reset:
      friendly_name: 'Licht wasruimte aan/uit bij beweging reset'
      hidden: true

    input_boolean.light_boiler_room_turn_on_motion_detected:
      hidden: true
