##
# fibaro_fgd212_landing_downstairs.yaml
#
# FIBARO Dimmer 2 FGD-212 (landing downstairs)
#
# @category   Home Assistant
# @package    Device packages
# @author     Jeroen Butenaerts
# @version    1.0
##

##
# Customize
##
homeassistant:
  customize:
    light.fibaro_system_fgd212_dimmer_2_level_14:
      friendly_name: 'Plafondlamp kelderportaal (S2)'
      hidden: true

    light.fibaro_system_fgd212_dimmer_2_level_15:
      friendly_name: 'Plafondlamp kelderportaal'
      icon: 'mdi:ceiling-light'

    sensor.fibaro_system_fgd212_dimmer_2_energy_8:
      friendly_name: 'Plafondlamp kelderportaal'

    zwave.fibaro_system_fgd212_dimmer_2_8:
      friendly_name: 'Plafondlamp kelderportaal'

  customize_glob:
    light.fibaro_system_fgd212_dimmer_2_level_15:
      group:
        group.lights_landing_downstairs:
          friendly_name: 'Plafondlamp'

    sensor.fibaro_system_fgd212_dimmer_2_energy_8:
      group:
        group.consumption_lighting:
          icon: 'mdi:ceiling-light'

    zwave.fibaro_system_fgd212_dimmer_2_8:
      group:
        group.zwave_devices:
          friendly_name: 'Dimmer kelderportaal'
