##
# light_all_off_alarm_armed_away.yaml
#
# Turn lights off when alarm is armed away
#
# @category   Home Assistant
# @package    Automations
# @author     Jeroen Butenaerts
# @version    1.0
##

##
# Automations
##
automation:
  ##
  # Turn off all lights when alarm is armed away
  ##
  - alias: 'Light all off alarm armed away'
    initial_state: on
    trigger:
      # When the state of the physical alarm is set to armed away
      platform: state
      entity_id: alarm_control_panel.woonveilig
      to: 'armed_away'
    condition:
      # While presence simulation is not activated
      condition: state
      entity_id: binary_sensor.routine_presence_simulation_active
      state: 'off'
    action:
      # Then turn off all lights
      service: light.turn_off
      entity_id: group.all_lights

##
# Customize
##
homeassistant:
  customize:
    automation.light_all_off_alarm_armed_away:
      friendly_name: 'Verlichting uitschakelen bij inschakelen alarm'
      hidden: true
