##
# light_garage_turn_on_motion.yaml
#
# Turn on the garage ceiling lights when motion is detected, auto off after 5 minutes
#
# @category   Home Assistant
# @package    Automations
# @author     Jeroen Butenaerts
# @version    1.0
##
input_boolean:
  light_garage_turn_on_motion_detected:
    initial: 'off'

automation:
  ##
  # Turn light on when motion is detected
  ##
  - alias: 'Light garage turn on motion detected'
    initial_state: on
    trigger:
      # When motion is detected on either sensor
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d0002ec3208
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d000257a829
        to: 'on'
    condition:
      # While the lights are off for at least 10 seconds
      condition: state
      entity_id: light.plafondlampen_garage
      state: 'off'
      for:
        seconds: 10
    action:
      # Then turn the lights on
      - service: light.turn_on
        data:
          entity_id: light.plafondlampen_garage
      # And register it
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.light_garage_turn_on_motion_detected

  ##
  # Turn light off when no motion is detected
  # - after 5 minutes when light was turned on through motion
  # - or after 60 minutes in any case
  ##
  - alias: 'Light garage turn off no motion detected'
    initial_state: on
    trigger:
      # When no motion is detected for 5 minutes on either sensor
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d0002ec3208
        to: 'off'
        for:
          minutes: 5
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d000257a829
        to: 'off'
        for:
          minutes: 5
    condition:
      condition: or
      conditions:
        - condition: and
          conditions:
            # While no motion is detected for 5 minutes on either other sensor
            - condition: state
              entity_id: binary_sensor.motion_sensor_158d0002ec3208
              state: 'off'
              for:
                minutes: 5
            - condition: state
              entity_id: binary_sensor.motion_sensor_158d000257a829
              state: 'off'
              for:
                minutes: 5
            # And there is a registration
            - condition: state
              entity_id: input_boolean.light_garage_turn_on_motion_detected
              state: 'on'
        - condition: and
          conditions:
            # Or no motion is detected for 60 minutes on both sensors
            - condition: state
              entity_id: binary_sensor.motion_sensor_158d0002ec3208
              state: 'off'
              for:
                minutes: 60
            - condition: state
              entity_id: binary_sensor.motion_sensor_158d000257a829
              state: 'off'
              for:
                minutes: 60
    action:
      # Then turn the light off
      service: light.turn_off
      data:
        entity_id: light.plafondlampen_garage
  ##
  # Reset detection when light is turned off
  ##
  - alias: 'Light garage turn on motion detected reset'
    initial_state: on
    trigger:
      # When the lights are turned off
      platform: state
      entity_id: light.plafondlampen_garage
      to: 'off'
    action:
      # Then clear the registration
      service: input_boolean.turn_off
      data:
        entity_id: input_boolean.light_garage_turn_on_motion_detected

##
# Customize
##
homeassistant:
  customize:
    automation.light_garage_turn_on_motion_detected:
      friendly_name: 'Licht garage aan bij beweging'
      hidden: true

    automation.light_garage_turn_off_no_motion_detected:
      friendly_name: 'Licht garage uit bij geen beweging'
      hidden: true

    automation.light_garage_turn_on_motion_detected_reset:
      friendly_name: 'Licht garage aan/uit bij beweging reset'
      hidden: true

    input_boolean.light_garage_turn_on_motion_detected:
      hidden: true
