##
# fibaro_fgd212.yaml
#
# FIBARO Dimmer 2 FGD-212
#
# @category   Home Assistant
# @package    Device packages
# @author     Jeroen Butenaerts
# @version    1.0
##

##
# Customize
##
homeassistant:
  customize_glob:
    "sensor.fibaro_system_fgd212_dimmer_2_alarm_level*":
      hidden: true

    "sensor.fibaro_system_fgd212_dimmer_2_alarm_type*":
      hidden: true

    "sensor.fibaro_system_fgd212_dimmer_2_exporting*":
      hidden: true

    "sensor.fibaro_system_fgd212_dimmer_2_heat*":
      hidden: true

    "sensor.fibaro_system_fgd212_dimmer_2_interval*":
      hidden: true

    "sensor.fibaro_system_fgd212_dimmer_2_power*":
      hidden: true

    "sensor.fibaro_system_fgd212_dimmer_2_power_management*":
      hidden: true

    "sensor.fibaro_system_fgd212_dimmer_2_previous_reading*":
      hidden: true

    "sensor.fibaro_system_fgd212_dimmer_2_sourcenodeid*":
      hidden: true

    "sensor.fibaro_system_fgd212_dimmer_2_system*":
      hidden: true
