##
# honeywell_evohome.yaml
#
# Honeywell EvoHome
#
# @category   Home Assistant
# @package    Devices
# @author     Jeroen Butenaerts
# @version    1.0
##
evohome:
  username: !secret honeywell_username
  password: !secret honeywell_password

##
# Customize
##
homeassistant:
  customize:
    climate.eethoek:
      friendly_name: 'Verwarming eethoek'

    climate.hal:
      friendly_name: 'Verwarming hal'

    climate.keuken:
      friendly_name: 'Verwarming keuken'

    climate.zithoek:
      friendly_name: 'Verwarming zithoek'

    climate.thuis:
      friendly_name: 'Verwarming huis'

  customize_glob:
    climate.hal:
      group:
        group.climate_entryway:
          friendly_name: 'Verwarming'

    climate.keuken:
      group:
        group.climate_kitchen:
          friendly_name: 'Verwarming'

    climate.thuis:
      group:
        group.view_home:
          friendly_name: 'Verwarming'
