##
# lg_webostv.yaml
#
# LG WebOS TV
#
# @category   Home Assistant
# @package    Device packages
# @author     Jeroen Butenaerts
# @version    1.0
##
media_player:
  - platform: webostv
    host: !secret webostv_host
    name: 'TV woonkamer'
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: !secret webostv_mac
    customize:
      sources:
        - hdmi2
        - netflix
        - nos
        - npo
        - spotify
        - youtube

##
# Customize
##
homeassistant:
  customize:
    media_player.tv_woonkamer:
      device_class: tv
      icon: 'mdi:television-classic'

  customize_glob:
    media_player.tv_woonkamer:
      group:
        group.devices_living_room:
          friendly_name: 'Televisie'
