##
# fibaro_fgd212_garage.yaml
#
# FIBARO Dimmer 2 FGD-212 (garage 1 & 2)
#
# @category   Home Assistant
# @package    Device packages
# @author     Jeroen Butenaerts
# @version    1.0
##
light:
  - platform: group
    name: 'Plafondlampen garage'
    entities:
      - light.fibaro_system_fgd212_dimmer_2_level_19
      - light.fibaro_system_fgd212_dimmer_2_level_21

##
# Customize
##
homeassistant:
  customize:
    light.fibaro_system_fgd212_dimmer_2_level_18:
      friendly_name: 'Plafondlamp garage 1 (S2)'
      hidden: true

    light.fibaro_system_fgd212_dimmer_2_level_19:
      friendly_name: 'Plafondlamp garage 1'
      hidden: true

    light.fibaro_system_fgd212_dimmer_2_level_20:
      friendly_name: 'Plafondlamp garage 2 (S2)'
      hidden: true

    light.fibaro_system_fgd212_dimmer_2_level_21:
      friendly_name: 'Plafondlamp garage 2'
      hidden: true

    light.plafondlampen_garage:
      icon: 'mdi:ceiling-light'

    sensor.fibaro_system_fgd212_dimmer_2_energy_10:
      friendly_name: 'Plafondlamp garage 1'

    sensor.fibaro_system_fgd212_dimmer_2_energy_11:
      friendly_name: 'Plafondlamp garage 2'

    zwave.fibaro_system_fgd212_dimmer_2_10:
      friendly_name: 'Plafondlamp garage 1'

    zwave.fibaro_system_fgd212_dimmer_2_11:
      friendly_name: 'Plafondlamp garage 2'

  customize_glob:
    light.plafondlampen_garage:
      group:
        group.lights_garage:
          friendly_name: 'Plafondlampen'

    sensor.fibaro_system_fgd212_dimmer_2_energy_10:
      group:
        group.consumption_lighting:
          icon: 'mdi:ceiling-light'

    sensor.fibaro_system_fgd212_dimmer_2_energy_11:
      group:
        group.consumption_lighting:
          icon: 'mdi:ceiling-light'

    zwave.fibaro_system_fgd212_dimmer_2_10:
      group:
        group.zwave_devices:
          friendly_name: 'Dimmer garage 1'

    zwave.fibaro_system_fgd212_dimmer_2_11:
      group:
        group.zwave_devices:
          friendly_name: 'Dimmer garage 2'
