##
# fibaro_fgd212_toilet.yaml
#
# FIBARO Dimmer 2 FGD-212 (toilet)
#
# @category   Home Assistant
# @package    Device packages
# @author     Jeroen Butenaerts
# @version    1.0
##

##
# Customize
##
homeassistant:
  customize:
    light.fibaro_system_fgd212_dimmer_2_level_12:
      friendly_name: 'Plafondlamp toilet (S2)'
      hidden: true

    light.fibaro_system_fgd212_dimmer_2_level_13:
      friendly_name: 'Plafondlamp toilet'
      icon: 'mdi:ceiling-light'

    sensor.fibaro_system_fgd212_dimmer_2_energy_7:
      friendly_name: 'Plafondlamp toilet'

    zwave.fibaro_system_fgd212_dimmer_2_7:
      friendly_name: 'Plafondlamp toilet'

  customize_glob:
    light.fibaro_system_fgd212_dimmer_2_level_13:
      group:
        group.lights_toilet:
          friendly_name: 'Plafondlamp'

    sensor.fibaro_system_fgd212_dimmer_2_energy_7:
      group:
        group.consumption_lighting:
          icon: 'mdi:ceiling-light'

    zwave.fibaro_system_fgd212_dimmer_2_7:
      group:
        group.zwave_devices:
          friendly_name: 'Dimmer toilet'
