##
# fibaro_fgd212_living.yaml
#
# FIBARO Dimmer 2 FGD-212 (living)
#
# @category   Home Assistant
# @package    Device packages
# @author     Jeroen Butenaerts
# @version    1.0
##

##
# Customize
##
homeassistant:
  customize:
    light.fibaro_system_fgd212_dimmer_2_level_3:
      friendly_name: 'Plafondlamp zithoek (S2)'
      hidden: true

    light.fibaro_system_fgd212_dimmer_2_level_4:
      friendly_name: 'Plafondlamp zithoek'
      icon: 'mdi:ceiling-light'
      state_card_mode: break-slider-toggle
      stretch_slider: true
      slider_theme:
        min: 1
        off_when_min: false
        report_when_not_changed: false

    sensor.fibaro_system_fgd212_dimmer_2_energy_2:
      friendly_name: 'Plafondlamp zithoek'

    zwave.fibaro_system_fgd212_dimmer_2_2:
      friendly_name: 'Plafondlamp zithoek'

  customize_glob:
    light.fibaro_system_fgd212_dimmer_2_level_4:
      group:
        group.lights_living_room:
          friendly_name: 'Plafondlamp zithoek'
        group.lights_blinds_living_room:
          friendly_name: 'Plafondlamp zithoek'

    sensor.fibaro_system_fgd212_dimmer_2_energy_2:
      group:
        group.consumption_lighting:
          icon: 'mdi:ceiling-light'

    zwave.fibaro_system_fgd212_dimmer_2_2:
      group:
        group.zwave_devices:
          friendly_name: 'Dimmer zithoek'
