##
# aeotec_zw100.yaml
#
# Aeotec ZW100 MultiSensor 6
#
# @category   Home Assistant
# @package    Device packages
# @author     Jeroen Butenaerts
# @version    1.0
##

##
# Components
##

##
# Customize
##
homeassistant:
  customize:
    binary_sensor.aeotec_multisensor_6_sensor:
      friendly_name: Beweging
      icon: mdi:walk

    sensor.aeotec_multisensor_6_alarm_level:
      friendly_name: Alarm niveau
      icon: mdi:alarm-bell

    sensor.aeotec_multisensor_6_alarm_type:
      friendly_name: Alarm type
      icon: mdi:alarm-bell

    sensor.aeotec_multisensor_6_burglar:
      friendly_name: Beweging/vibratie
      icon: mdi:account-alert

    sensor.aeotec_multisensor_6_luminance:
      friendly_name: Lichtsterkte
      icon: mdi:weather-sunny

    sensor.aeotec_multisensor_6_relative_humidity:
      friendly_name: Luchtvochtigheid
      icon: mdi:water-percent

    sensor.aeotec_multisensor_6_sourcenodeid:
      friendly_name: Source node
      icon: mdi:network

    sensor.aeotec_multisensor_6_temperature:
      friendly_name: Temperatuur
      icon: mdi:thermometer

    sensor.aeotec_multisensor_6_ultraviolet:
      friendly_name: Ultraviolette straling
      icon: mdi:white-balance-sunny

#    zwave.aeotec_multisensor_6:

##
# Groups
##
group:
  aeotec_multisensor_6:
    entities:
      - binary_sensor.aeotec_multisensor_6_sensor
      - sensor.aeotec_multisensor_6_alarm_level
      - sensor.aeotec_multisensor_6_alarm_type
      - sensor.aeotec_multisensor_6_burglar
      - sensor.aeotec_multisensor_6_luminance
      - sensor.aeotec_multisensor_6_relative_humidity
      - sensor.aeotec_multisensor_6_sourcenodeid
      - sensor.aeotec_multisensor_6_temperature
      - sensor.aeotec_multisensor_6_ultraviolet
    icon: mdi:eye-outline
    name: Aeotec MultiSensor
    view: false

##
# Scenes
##

##
# Automation
##

##
# Scripts
##
