##
# apple_tv.yaml
#
# Apple TV v4
#
# @category   Home Assistant
# @package    Devices
# @author     Jeroen Butenaerts
# @version    1.0
##
apple_tv:
  - name: 'appletv_bedroom'
    host: !secret apple_tv_bedroom_host
    login_id: !secret apple_tv_bedroom_login_id
#    credentials: !secret apple_tv_bedroom_credentials
    start_off: true
  - name: 'appletv_living'
    host: !secret apple_tv_living_host
    login_id: !secret apple_tv_living_login_id
#    credentials: !secret apple_tv_living_credentials
    start_off: true

##
# Customize
##
homeassistant:
  customize:
    media_player.appletv_bedroom:
      friendly_name: 'Apple TV slaapkamer'
      icon: 'mdi:apple'

    media_player.appletv_living:
      friendly_name: 'Apple TV woonkamer'
      icon: 'mdi:apple'

    remote.appletv_bedroom:
      friendly_name: 'Apple TV slaapkamer'
      hidden: true

    remote.appletv_living:
      friendly_name: 'Apple TV woonkamer'
      hidden: true

  customize_glob:
    media_player.appletv_bedroom:
      group:
        group.devices_bedroom:
          friendly_name: 'Apple TV'

    media_player.appletv_living:
      group:
        group.devices_living_room:
          friendly_name: 'Apple TV'
