##
# denon_avr.yaml
#
# DENON AVR-X1300W
#
# @category   Home Assistant
# @package    Devices
# @author     Jeroen Butenaerts
# @version    1.0
##
media_player:
  - platform: denonavr
    host: !secret denonavr_host
    name: 'Receiver woonkamer'
    show_all_sources: false

##
# Customize
##
homeassistant:
  customize:
    media_player.receiver_woonkamer:
      icon: 'mdi:speaker'

  customize_glob:
    media_player.receiver_woonkamer:
      group:
        group.devices_living_room:
          friendly_name: 'Receiver'
