##
# fibaro_fgwp102.yaml
#
# FIBARO Wall Plug FGWP-102
#
# @category   Home Assistant
# @package    Device packages
# @author     Jeroen Butenaerts
# @version    1.0
##

##
# Customize
##
homeassistant:
  customize:
    # Wall Plug espressomachine (node 8)
    sensor.fibaro_system_fgwpef_wall_plug_gen5_energy:
      friendly_name: 'Espressomachine'

    switch.fibaro_system_fgwpef_wall_plug_gen5_switch:
      friendly_name: 'Espressomachine'
      icon: 'mdi:coffee'

    zwave.fibaro_system_fgwpef_wall_plug_gen5:
      friendly_name: 'Stekker espressomachine'

  customize_glob:
    "sensor.fibaro_system_fgwpef_wall_plug_gen5_alarm_level*":
      hidden: true

    "sensor.fibaro_system_fgwpef_wall_plug_gen5_alarm_type*":
      hidden: true

    "sensor.fibaro_system_fgwpef_wall_plug_gen5_exporting*":
      hidden: true

    "sensor.fibaro_system_fgwpef_wall_plug_gen5_power*":
      hidden: true

    "sensor.fibaro_system_fgwpef_wall_plug_gen5_power_management*":
      hidden: true

    "sensor.fibaro_system_fgwpef_wall_plug_gen5_sourcenodeid*":
      hidden: true

    sensor.fibaro_system_fgwpef_wall_plug_gen5_energy:
      group:
        group.consumption_devices:
          icon: 'mdi:coffee'
