##
# google_cast.yaml
#
# Google Cast
#
# @category   Home Assistant
# @package    Devices
# @author     Jeroen Butenaerts
# @version    1.0
##
cast:
  media_player:
    - host: !secret cast_host_chromecast_bedroom
    - host: !secret cast_host_chromecast_living
    - host: !secret cast_host_googlehome_basement
    - host: !secret cast_host_googlehome_kitchen
    - host: !secret cast_host_googlehome_landing
    - host: !secret cast_host_googlehome_living

##
# Customize
##
homeassistant:
  customize:
    media_player.chromecast_bedroom:
      friendly_name: 'Chromecast slaapkamer'
      icon: 'mdi:cast'

    media_player.chromecast_living:
      friendly_name: 'Chromecast woonkamer'
      icon: 'mdi:cast'

    media_player.googlehome_basement:
      friendly_name: 'Google Home kelder'
      icon: 'mdi:google-home'

    media_player.googlehome_kitchen:
      friendly_name: 'Google Home keuken'
      icon: 'mdi:google-home'

    media_player.googlehome_landing:
      friendly_name: 'Google Home overloop'
      icon: 'mdi:google-home'

    media_player.googlehome_living:
      friendly_name: 'Google Home eethoek'
      icon: 'mdi:google-home'

  customize_glob:
    media_player.chromecast_bedroom:
      group:
        group.devices_bedroom:
          friendly_name: 'Chromecast'

    media_player.chromecast_living:
      group:
        group.devices_living_room:
          friendly_name: 'Chromecast'

    media_player.googlehome_basement:
      group:
        group.devices_basement:
          friendly_name: 'Google Home'

    media_player.googlehome_kitchen:
      group:
        group.devices_kitchen:
          friendly_name: 'Google Home'

    media_player.googlehome_landing:
      group:
        group.devices_landing_upstairs:
          friendly_name: 'Google Home'

    media_player.googlehome_living:
      group:
        group.devices_living_room:
          friendly_name: 'Google Home'
