##
# sensative_strips_comfort.yaml
#
# Sensative Strips Comfort
#
# @category   Home Assistant
# @package    Packages
# @author     Jeroen Butenaerts
# @version    1.0
##
sensor:
  - platform: template
    sensors:
      sensative_strips_comfort_battery:
        device_class: battery
        friendly_name: 'Batterij buitenmeter'
        unit_of_measurement: '%'
        value_template: >-
          {%- if states.zwave.sensative_strips_comfort -%}
            {{ (state_attr('zwave.sensative_strips_comfort', 'battery_level') or 0) }}
          {%- else -%}
            'unknown'
          {%- endif -%}
        icon_template: >-
          {% set battery_level = state_attr('zwave.sensative_strips_comfort', 'battery_level')|int('unknown') %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}
##
# Customize
##
homeassistant:
  customize:
    sensor.sensative_strips_comfort_luminance:
      friendly_name: 'Lichtsterkte buiten'
    sensor.sensative_strips_comfort_temperature:
      friendly_name: 'Temperatuur buiten'
      hidden: true
  customize_glob:
    binary_sensor.sensative_strips_comfort_sensor:
      hidden: true
    sensor.sensative_strips_comfort_alarm_level:
      hidden: true
    sensor.sensative_strips_comfort_alarm_type:
      hidden: true
    sensor.sensative_strips_comfort_burglar:
      hidden: true
    sensor.sensative_strips_comfort_flood:
      hidden: true
    sensor.sensative_strips_comfort_heat:
      hidden: true
    sensor.sensative_strips_comfort_luminance:
      group:
        group.climate_outdoor:
          friendly_name: 'Lichtsterkte'
    sensor.sensative_strips_comfort_moisture:
      hidden: true
    sensor.sensative_strips_comfort_sourcenodeid:
      hidden: true
    sensor.sensative_strips_comfort_temperature:
      group:
        group.climate_outdoor:
          friendly_name: 'Temperatuur'
    zwave.sensative_strips_comfort:
      group:
        group.zwave_devices:
          friendly_name: 'Buitenmeter'
