##
# synology_ds114.yaml
#
# Synology DiskStation DS114
#
# @category   Home Assistant
# @package    Devices
# @author     Jeroen Butenaerts
# @version    1.0
##

##
# Components
##
sensor:
  - platform: synologydsm
    host: !secret ds114_host
    password: !secret ds114_password
    username: !secret ds114_username
    monitored_conditions:
      - cpu_total_load
      - memory_available_real
      - memory_real_usage
      - memory_total_real
      - network_down
      - network_up
      - disk_smart_status
      - volume_status
      - volume_size_total
      - volume_size_used

#  - platform: template
#    sensors:
#      free_space_volume_1:
#        friendly_name: "Beschikbare ruimte"
#        unit_of_measurement: 'MB'
#        value_template: "{{ states('sensor.volume_size_total') - ( states('sensor.volume_size_used')|float / 1024 ) }}"
#        icon_template: mdi:chart-pie

switch:
  - platform: wake_on_lan
    mac_address: !secret ds114_mac
    host: !secret ds114_host
    name: Synology DS114

##
# Customize
##
homeassistant:
  customize:
    sensor.cpu_load_total:
      friendly_name: Processorgebruik
    sensor.disk_smart_status:
      hidden: true
    sensor.memory_available_real:
      hidden: true
    sensor.memory_usage_real:
      friendly_name: Geheugengebruik
    sensor.memory_total_real:
      hidden: true
    sensor.network_down:
      friendly_name: Download snelheid
    sensor.network_up:
      friendly_name: Upload snelheid
    sensor.status_sda:
      hidden: true
    sensor.status_smart_sda:
      hidden: true
    sensor.status_volume_1:
      hidden: true
    sensor.temperature_sda:
      friendly_name: Temperatuur
    sensor.total_size_volume_1:
      hidden: true
    sensor.used_space_volume_1:
      hidden: true

##
# Groups
##
group:
  synology_ds114:
    entities:
      - switch.synology_ds114
      - sensor.volume_status
#      - sensor.free_space_volume_1
      - sensor.cpu_load_total
      - sensor.memory_usage_real
      - sensor.temperature_sda
      - sensor.network_down
      - sensor.network_up
    icon: mdi:server
    name: Bestandsserver (DS114)
    view: false

##
# Scenes
##

##
# Automation
##

##
# Scripts
##
