##
# alarm_control_panel.yaml
#
# Manual alarm control panel
#
# @category   Home Assistant
# @package    Component packages
# @author     Jeroen Butenaerts
# @version    1.0
##
input_number:
  alarm_entry_delay_time:
    unit_of_measurement: 's'
    initial: 10
    min: 10
    max: 60
    step: 10
  alarm_exit_delay_time:
    unit_of_measurement: 's'
    initial: 30
    min: 10
    max: 60
    step: 10
  alarm_trigger_time:
    unit_of_measurement: 's'
    initial: 300
    min: 30
    max: 600
    step: 30

alarm_control_panel:
  - platform: manual
    name: 'virtual_alarm'
#    pending_time: "{{ states('input_number.alarm_exit_delay_time') | int }}"
    pending_time: 30
#    delay_time: "{{ states('input_number.alarm_entry_delay_time') | int }}"
    delay_time: 10
#    trigger_time: "{{ states('input_number.alarm_trigger_time') | int }}"
    trigger_time: 300
##
# Customize
##
homeassistant:
  customize:
    alarm_control_panel.virtual_alarm:
      friendly_name: 'Virtueel alarm'

    input_number.alarm_entry_delay_time:
      friendly_name: 'Alarm toegangsvertraging'
      icon: 'mdi:timer'

    input_number.alarm_exit_delay_time:
      friendly_name: 'Alarm uitgangsvertraging'
      icon: 'mdi:timer'

    input_number.alarm_trigger_time:
      friendly_name: 'Alarm looptijd'
      icon: 'mdi:timer'
