##
# consumption.yaml
#
# Consumption group
#
# @category   Home Assistant
# @package    Groups
# @author     Jeroen Butenaerts
# @version    1.0
##
group:
  # Devices
  consumption_devices:
    name: 'Apparaten'
    icon: 'mdi:power-socket-eu'
    control: 'hidden'
    entities:
      - sensor.fibaro_system_fgwpef_wall_plug_gen5_energy
      - sensor.plug_dishwasher_energy
      - sensor.plug_washer_energy

  # Lights
  consumption_lighting:
    name: 'Verlichting'
    icon: 'mdi:lightbulb'
    control: 'hidden'
    entities:
      - sensor.fibaro_system_fgd212_dimmer_2_energy
      - sensor.fibaro_system_fgd212_dimmer_2_energy_10
      - sensor.fibaro_system_fgd212_dimmer_2_energy_11
      - sensor.fibaro_system_fgd212_dimmer_2_energy_3
      - sensor.fibaro_system_fgd212_dimmer_2_energy_8
      - sensor.fibaro_system_fgd212_dimmer_2_energy_6
      - sensor.fibaro_system_fgd212_dimmer_2_energy_7
      - sensor.fibaro_system_fgd212_dimmer_2_energy_9
      - sensor.fibaro_system_fgd212_dimmer_2_energy_2

##
# Customize
##
homeassistant:
  customize:
    group.consumption_devices:
      order: 1

    group.consumption_lighting:
      order: 2
