##
# home.yaml
#
# Home group
#
# @category   Home Assistant
# @package    Groups
# @author     Jeroen Butenaerts
# @version    1.0
##
group:
  # Blinds
  home_blinds:
    name: 'Blinds'
    icon: 'mdi:blinds'
    view: false
    entities:
      - cover.living_room_all

  # Lights
  home_lights:
    name: 'Lights'
    icon: 'mdi:lightbulb'
    view: false
    entities:
      - group.lights_living_room
      - group.lights_kitchen
      - group.lights_entryway
      - group.lights_boiler_room
      - group.lights_garage
      - group.lights_landing_downstairs

  # Presence
  home_presence:
    name: 'Presence'
    icon: 'mdi:account-multiple'
    control: 'hidden'
    view: false
    entities:
      - person.jeroen
#      - device_tracker.iphone_jeroen
      - person.veerle
#      - device_tracker.iphone_veerle
      - switch.person_presence_simulation

  # Security
  home_security:
    name: 'Security'
    icon: 'mdi:shield-home'
    control: 'hidden'
    view: false
    entities:
      - binary_sensor.door_window_sensor_all
      - binary_sensor.motion_sensor_all
      - binary_sensor.smoke_sensor_all
      - binary_sensor.natgas_sensor_all
      - binary_sensor.water_leak_sensor_all
      - group.security_door_window
      - group.security_motion
      - group.security_smoke
      - group.security_natgas
      - group.security_water_leak

##
# Customize
##
homeassistant:
  customize:
    group.home_blinds:
      friendly_name: 'Blindering'

    group.home_lights:
      friendly_name: 'Verlichting'

    group.home_presence:
      friendly_name: 'Aanwezigheid'

    group.home_security:
      friendly_name: 'Beveiliging'
