##
# door_window_sensor_158d00019fd4c6.yaml
#
# Xiaomi Aqara door/window sensor
#
# @category   Home Assistant
# @package    Devices
# @author     Jeroen Butenaerts
# @version    1.0
##
sensor:
  - platform: template
    sensors:
      door_window_sensor_158d00019fd4c6_battery:
        device_class: battery
        unit_of_measurement: '%'
        value_template: "{{ state_attr('binary_sensor.door_window_sensor_158d00019fd4c6', 'battery_level')|int }}"
        icon_template: >
          {% set battery_level = state_attr('binary_sensor.door_window_sensor_158d00019fd4c6', 'battery_level')|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}

##
# Customize
##
homeassistant:
  customize:
    binary_sensor.door_window_sensor_158d00019fd4c6:
      device_class: garage_door
      friendly_name: 'Garagepoort'

    sensor.door_window_sensor_158d00019fd4c6_battery:
      friendly_name: 'Batterij deur-/raamcontact garagepoort'

  customize_glob:
    sensor.door_window_sensor_158d00019fd4c6_battery:
      group:
        group.battery_levels:
          friendly_name: 'Deur-/raamcontact garagepoort'
