##
# smoke_sensor_158d0001e80a3c.yaml
#
# Xiaomi Aqara smoke sensor
#
# @category   Home Assistant
# @package    Devices
# @author     Jeroen Butenaerts
# @version    1.0
##
sensor:
  - platform: template
    sensors:
      smoke_sensor_158d0001e80a3c_battery:
        device_class: battery
        unit_of_measurement: '%'
        value_template: "{{ state_attr('binary_sensor.smoke_sensor_158d0001e80a3c', 'battery_level')|int }}"
        icon_template: >
          {% set battery_level = state_attr('binary_sensor.smoke_sensor_158d0001e80a3c', 'battery_level')|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}

##
# Customize
##
homeassistant:
  customize:
    binary_sensor.smoke_sensor_158d0001e80a3c:
      device_class: smoke
      friendly_name: 'Rook wasruimte'

    sensor.smoke_sensor_158d0001e80a3c_battery:
      friendly_name: 'Batterij rookdetector wasruimte'

  customize_glob:
    binary_sensor.smoke_sensor_158d0001e80a3c:
      group:
        group.security_smoke:
          friendly_name: 'Wasruimte'

    sensor.smoke_sensor_158d0001e80a3c_battery:
      group:
        group.battery_levels:
          friendly_name: 'Rookdetector wasruimte'
