##
# covers_ground_floor_open_close_dawn_dusk.yaml
#
# Automatically open/close the ground floor covers when nobody is home for dawn and dusk
#
# @category   Home Assistant
# @package    Automations
# @author     Jeroen Butenaerts
# @version    1.0
##
input_number:
  covers_ground_floor_open_close_dawn_dusk_lux_threshold:
    name: 'Threshold value for opening and closing the ground floor covers'
    unit_of_measurement: 'lux'
    initial: 50
    min: 0
    max: 100
    step: 1

input_datetime:
  covers_ground_floor_close_dusk_time:
    name: 'Time at which to close the ground floor covers (dusk)'
    has_date: false
    has_time: true
    initial: '19:00'
  covers_ground_auto_floor_dawn_time:
    name: 'Time at which to open the ground floor covers (dawn)'
    has_date: false
    has_time: true
    initial: '07:30'

automation:
  ##
  # Covers ground floor open at dawn
  ##
  - alias: 'Covers ground floor open at dawn'
    initial_state: on
    trigger:
      # When current time equals specified opening time
      - platform: template
        value_template: "{{ states('sensor.time') == state_attr('input_datetime.covers_ground_auto_floor_dawn_time', 'timestamp')|int|timestamp_custom('%H:%M', false) }}"
      # Or outside luminance is above or equal to specified threshold value
      - platform: template
        value_template: "{{ states('sensor.sensative_strips_comfort_luminance')|int >= states('input_number.covers_ground_floor_open_close_dawn_dusk_lux_threshold')|int }}"
    condition:
      # While current time is greater than or equal to specified opening time
      - condition: template
        value_template: "{{ states('sensor.time') >= state_attr('input_datetime.covers_ground_auto_floor_dawn_time', 'timestamp')|int|timestamp_custom('%H:%M', false) }}"
      # And outside luminance is above or equal to specified threshold value
      - condition: template
        value_template: "{{ states('sensor.sensative_strips_comfort_luminance')|int >= states('input_number.covers_ground_floor_open_close_dawn_dusk_lux_threshold')|int }}"
      # And no person is home
      - condition: state
        entity_id: binary_sensor.person_any_home
        state: 'off'
    action:
      # Then open all ground level covers
      service: cover.open_cover
      entity_id: cover.living_room_all

  ##
  # Covers ground floor close at dusk
  ##
  - alias: 'Covers ground floor close at dusk'
    initial_state: on
    trigger:
      # When current time equals specified closing time
      - platform: template
        value_template: "{{ states('sensor.time') == state_attr('input_datetime.covers_ground_floor_close_dusk_time', 'timestamp')|int|timestamp_custom('%H:%M', false) }}"
      # Or outside luminance is below or equal to specified threshold value
      - platform: template
        value_template: "{{ states('sensor.sensative_strips_comfort_luminance')|int <= states('input_number.covers_ground_floor_open_close_dawn_dusk_lux_threshold')|int }}"
    condition:
      # While current time is greater than or equal to specified closing time
      - condition: template
        value_template: "{{ states('sensor.time') >= state_attr('input_datetime.covers_ground_floor_close_dusk_time', 'timestamp')|int|timestamp_custom('%H:%M', false) }}"
      # And outside luminance is below or equal to specified threshold value
      - condition: template
        value_template: "{{ states('sensor.sensative_strips_comfort_luminance')|int <= states('input_number.covers_ground_floor_open_close_dawn_dusk_lux_threshold')|int }}"
      # And no person is home
      - condition: state
        entity_id: binary_sensor.person_any_home
        state: 'off'
    action:
      # Then close all ground level covers
      service: cover.close_cover
      entity_id: cover.living_room_all

##
# Customize
##
homeassistant:
  customize:
    automation.covers_ground_floor_open_at_dawn:
      friendly_name: 'Raambekleding BG openen in de ochtend'
      hidden: true

    automation.covers_ground_floor_close_at_dusk:
      friendly_name: 'Raambekleding BG sluiten in de avond'
      hidden: true

    input_number.covers_ground_floor_open_close_dawn_dusk_lux_threshold:
      friendly_name: 'Raambekleding BG openen/sluiten in de ochtend/avond drempelwaarde lichtsterkte'

    input_datetime.covers_ground_floor_close_dusk_time:
      friendly_name: 'Raambekleding BG sluiten in de avond drempelwaarde tijd'

    input_datetime.covers_ground_auto_floor_dawn_time:
      friendly_name: 'Raambekleding BG openen in de ochtend drempelwaarde tijd'
