##
# scene_activity_watching_movie.yaml
#
# Set up for watching movie
#
# @category   Home Assistant
# @package    Scenes
# @author     Jeroen Butenaerts
# @version    1.0
##
scene:
  - name: 'activity_watching_movie'
    entities:
      cover.blindering_woonkamer:
        state: 'closed'
      light.fibaro_system_fgd212_dimmer_2_level_4: # Living
        state: off
        transition: 5
      light.tv_lamp:
        state: on
        brightness_pct: 25
        transition: 5
      light.fibaro_system_fgd212_dimmer_2_level_2: # Dining
        state: off
        transition: 5
      light.kastverlichting:
        state: off
        transition: 5
      light.livingwhites_plug_1:
        state: on
        brightness_pct: 25
        transition: 5
      light.fibaro_system_fgd212_dimmer_2_level_11: # Kitchen
        state: off
        transition: 5
      light.werkbladverlichting:
        state: on
        brightness_pct: 25
        transition: 5
  - name: 'activity_pausing_movie'
    entities:
      light.fibaro_system_fgd212_dimmer_2_level_4: # Living
        state: on
        brightness_pct: 5
        transition: 5
      light.tv_lamp:
        state: on
        brightness_pct: 50
        transition: 5
      light.fibaro_system_fgd212_dimmer_2_level_2: # Dining
        state: on
        brightness_pct: 5
        transition: 5
      light.kastverlichting:
        state: on
        brightness_pct: 25
        transition: 5
      light.livingwhites_plug_1:
        state: on
        brightness_pct: 50
        transition: 5
      light.fibaro_system_fgd212_dimmer_2_level_11: # Kitchen
        state: off
        transition: 5
      light.werkbladverlichting:
        state: on
        brightness_pct: 50
        transition: 5

##
# Customize
##
homeassistant:
  customize:
    scene.activity_watching_movie:
      friendly_name: 'Film afspelen'
      icon: 'mdi:movie'
    scene.activity_pausing_movie:
      friendly_name: 'Film pauzeren'
      icon: 'mdi:movie-outline'
