##
# scene_activity_cooking.yaml
#
# Set up for cooking
#
# @category   Home Assistant
# @package    Scenes
# @author     Jeroen Butenaerts
# @version    1.0
##
scene:
  - name: 'activity_cooking'
    entities:
      light.fibaro_system_fgd212_dimmer_2_level_11: # Kitchen
        state: on
        brightness_pct: 50
        transition: 2
      light.werkbladverlichting:
        state: on
        brightness_pct: 100
        transition: 2

##
# Customize
##
homeassistant:
  customize:
    scene.activity_cooking:
      friendly_name: 'Koken'
      icon: 'mdi:chef-hat'
