##
# gosund_sp111_washer.yaml
#
# Gosund SP111 (washer)
#
# @category   Home Assistant
# @package    Device packages
# @author     Jeroen Butenaerts
# @version    1.0
##
sensor:
  - platform: mqtt
    name: 'Plug washer energy'
    state_topic: 'tele/sonoff02/SENSOR'
    value_template: "{{ value_json['ENERGY']['Total'] }}"
    unit_of_measurement: 'kWh'

  - platform: mqtt
    name: 'Plug washer power'
    state_topic: 'tele/sonoff02/SENSOR'
    value_template: "{{ value_json['ENERGY']['Power'] }}"
    unit_of_measurement: 'W'

  - platform: mqtt
    name: 'Plug washer voltage'
    state_topic: 'tele/sonoff02/SENSOR'
    value_template: "{{ value_json['ENERGY']['Voltage'] }}"
    unit_of_measurement: 'V'

  - platform: mqtt
    name: 'Plug washer current'
    state_topic: 'tele/sonoff02/SENSOR'
    value_template: "{{ value_json['ENERGY']['Current'] }}"
    unit_of_measurement: 'A'

  - platform: mqtt
    name: 'Plug washer uptime'
    state_topic: 'tele/sonoff02/UPTIME'
    value_template: "{{ value_json.uptime }}"
    unit_of_measurement: 'U'

##
# Customize
##
homeassistant:
  customize:
    sensor.plug_washer_enery:
      friendly_name: 'Stroomverbruik wasmachine'

    sensor.plug_washer_power:
      friendly_name: 'Stroom wasmachine'

    sensor.plug_washer_voltage:
      friendly_name: 'Voltage wasmachine'

    sensor.plug_washer_current:
      friendly_name: 'Stroomsterkte wasmachine'

    sensor.plug_washer_uptime:
      friendly_name: 'Bedrijfstijd wasmachine'
