##
# gosund_sp111_dishwasher.yaml
#
# Gosund SP111 (dishwasher)
#
# @category   Home Assistant
# @package    Device packages
# @author     Jeroen Butenaerts
# @version    1.0
##
sensor:
  - platform: mqtt
    name: 'Plug dishwasher energy'
    state_topic: 'tele/sonoff01/SENSOR'
    value_template: "{{ value_json['ENERGY']['Total'] }}"
    unit_of_measurement: 'kWh'

  - platform: mqtt
    name: 'Plug dishwasher power'
    state_topic: 'tele/sonoff01/SENSOR'
    value_template: "{{ value_json['ENERGY']['Power'] }}"
    unit_of_measurement: 'W'

  - platform: mqtt
    name: 'Plug dishwasher voltage'
    state_topic: 'tele/sonoff01/SENSOR'
    value_template: "{{ value_json['ENERGY']['Voltage'] }}"
    unit_of_measurement: 'V'

  - platform: mqtt
    name: 'Plug dishwasher current'
    state_topic: 'tele/sonoff01/SENSOR'
    value_template: "{{ value_json['ENERGY']['Current'] }}"
    unit_of_measurement: 'A'

  - platform: mqtt
    name: 'Plug dishwasher uptime'
    state_topic: 'tele/sonoff01/UPTIME'
    value_template: "{{ value_json.uptime }}"
    unit_of_measurement: 'U'

##
# Customize
##
homeassistant:
  customize:
    sensor.plug_dishwasher_enery:
      friendly_name: 'Stroomverbruik vaatwasser'

    sensor.plug_dishwasher_power:
      friendly_name: 'Stroom vaatwasser'

    sensor.plug_dishwasher_voltage:
      friendly_name: 'Voltage vaatwasser'

    sensor.plug_dishwasher_current:
      friendly_name: 'Stroomsterkte vaatwasser'

    sensor.plug_dishwasher_uptime:
      friendly_name: 'Bedrijfstijd vaatwasser'
