##
# zwave.yaml
#
# Z-Wave.Me RaZberry v2
#
# @category   Home Assistant
# @package    Packages
# @author     Jeroen Butenaerts
# @version    1.0
##

##
# Components
##
zwave:
  usb_path: /dev/ttyAMA0
  network_key: "0xA2, 0x66, 0x08, 0xAF, 0x2C, 0x90, 0x9C, 0xEE, 0xA7, 0x16, 0x5B, 0x9E, 0x77, 0xD3, 0x56, 0xB1"
  polling_interval: 30000

##
# Customize
##
homeassistant:
  customize_glob:
    zwave.zwaveme_razberry_controller_2016_zwave:
      group:
        group.zwave_devices:
          friendly_name: Controller

##
# Groups
##

##
# Scenes
##

##
# Automation
##

##
# Scripts
##
